CREATE DATABASE customer_behavior;

USE customer_behavior;

SELECT *
FROM customer
LIMIT 20;

#-- What is the total revenue generated by male vs. female customers?
SELECT gender,sum(purchase_amount) as Total_Revenue
FROM customer
GROUP BY gender;

#-- Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id,discount_applied,purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount  > (SELECT avg(purchase_amount) AS Average_Amount
FROM customer);

#--  Which are the top 5 products with the highest average review rating?
SELECT item_purchased,avg(review_rating) AS Average_Rating
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;

#-- Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,avg(purchase_amount) Average_Amount
FROM customer
WHERE shipping_type = 'Standard' OR shipping_type = 'Express'
GROUP BY shipping_type;

#-- Do subscribed customers spend more? Compare average spend and total revenue 
#--between subscribers and non-subscribers.
SELECT subscription_status,avg(purchase_amount) AS Avg_Amount,
sum(purchase_amount) AS Total_Amount
FROM customer
GROUP BY subscription_status;

#-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND((sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / Count(Customer_id)) * 100,2) as Percentage_of_purchase
FROM customer
GROUP BY item_purchased
ORDER BY Percentage_of_Purchase DESC
LIMIT 5;

#-- Segment customers into New, Returning, and Loyal based on their total 
#-- number of previous purchases, and show the count of each segment. 
WITH Customer_Segment as
(SELECT customer_id,
CASE
WHEN previous_purchases = 1 THEN "New"
WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
ELSE "Loyal"
END AS customer_segment
FROM customer)

SELECT customer_segment,count(customer_id) AS Total_Customer
FROM Customer_Segment
GROUP BY customer_segment;

#-- What are the top 3 most purchased products within each category? 
WITH Total_amount as 
(SELECT category,item_purchased,Count(customer_id) as Total_purchase
FROM customer
GROUP BY category,item_purchased),

Ranked as

(SELECT category,item_purchased,Total_purchase,
row_number() over(partition by category order by Total_purchase DESC) as Ranks
FROM Total_amount)

SELECT category,item_purchased,Total_purchase,Ranks
FROM Ranked
WHERE Ranks <= 3;

#-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,COUNT(customer_id) AS repeat_buyers
FROM customer
where previous_purchases > 5 
GROUP BY subscription_status;

#--OR-------------------
SELECT count(customer_id) Total_Buyers,
sum(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) as Subscribed,
ROUND(sum(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) / count(customer_id) * 100,2) as Subscription_Percentage
FROM customer
WHERE previous_purchases > 5;

#-- What is the revenue contribution of each age group? 
SELECT age_group,sum(purchase_amount) as Total_amount
FROM customer
GROUP BY age_group
ORDER BY Total_amount DESC;

#--revenue contribution %
SELECT age_group,ROUND((sum(purchase_amount) / sum(sum(purchase_amount)) over()) * 100,2) as Revenue_Contribution_Percentage
FROM customer
GROUP BY age_group
ORDER BY Revenue_Contribution_Percentage DESC;